lojasvarejistasapp/urls.py
from django.urls import path, include
from . import views

urlpatterns = [

# URL PARA HOME
    path('',views.home, name='home'),
    path('home/',views.home, name='home'),

# URL PARA CLIENTES
    path('cliente/',views.cliente, name='cliente'),
    path('cadastrar_cliente/',views.cadastrar_cliente, name='cadastrar_cliente'),
    path('excluir_cliente/<int:cliente_id>',views.excluir_cliente, name='excluir_cliente'),
    path('editar_cliente/<int:cliente_id>',views.editar_cliente, name='editar_cliente'),

# URL PARA DEPENDENTE
    path('dependente/',views.dependente, name='dependente'),
    path('cadastrar_dependente/',views.cadastrar_dependente, name='cadastrar_dependente'),
    path('excluir_dependente/<int:dependente_id>',views.excluir_dependente, name='excluir_dependente'),
    path('editar_dependente/<int:dependente_id>',views.editar_dependente, name='editar_dependente'),

# URL PARA PRODUTO
    path('produto/',views.produto, name='produto'),
    path('cadastrar_produto/',views.cadastrar_produto, name='cadastrar_produto'),
    path('excluir_produto/<int:produto_id>',views.excluir_produto, name='excluir_produto'),
    path('editar_produto/<int:produto_id>',views.editar_produto, name='editar_produto'),

    
# URL PARA FORNECEDOR
    path('fornecedor/',views.fornecedor, name='fornecedor'),
    path('cadastrar_fornecedor/',views.cadastrar_fornecedor, name='cadastrar_fornecedor'),
    path('excluir_fornecedor/<int:fornecedor_id>',views.excluir_fornecedor, name='excluir_fornecedor'),
    path('editar_fornecedor/<int:fornecedor_id>',views.editar_fornecedor, name='editar_fornecedor'),

# URL PARA LOJA
    path('loja/',views.loja, name='loja'),
    path('cadastrar_loja/',views.cadastrar_loja, name='cadastrar_loja'),
    path('excluir_loja/<int:loja_id>',views.excluir_loja, name='excluir_loja'),
    path('editar_loja/<int:loja_id>',views.editar_loja, name='editar_loja'),

# URL PARA VENDA
    path('pedido/',views.pedido, name='pedido'),
    path('cadastrar_pedido/',views.cadastrar_pedido, name='cadastrar_pedido'),
    path('excluir_pedido/<int:pedido_id>',views.excluir_pedido, name='excluir_pedido'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lojasvarejistasapp.urls')),
]

lojasvarejistasapp/models.py
from django.db import models

class tab_cliente(models.Model):
    nomeCliente = models.CharField(max_length=60, blank=True, null=True)
    cpf = models.CharField(max_length=20, blank=True, null=True,unique=True)
    telefone = models.CharField(max_length=15, blank=False,null=False, unique=True)
    endereco = models.CharField(max_length=30, blank=True)
    programaPTS = models.BooleanField(default=False)
    totalPontos = models.IntegerField(blank=True, null=True)
    def __str__(self):
        return self.nomeCliente

class tab_dependente(models.Model):
    nomeDependente = models.CharField(max_length=60, blank=False)
    parentesco = models.CharField(max_length=60, blank=False)
    #ForeignKeys
    Cliente = models.ForeignKey(tab_cliente, on_delete=models.CASCADE)
    def __str__(self):
        return self.nomeDependente

class tab_loja(models.Model):
    nomeLoja = models.CharField(max_length=60, unique= True ,blank=False)
    endereco = models.CharField(max_length=60, blank=False)
    seg_sex = models.CharField(max_length=60, blank=True)
    sab = models.CharField(max_length=60, blank=True)
    dom = models.CharField(max_length=60, blank=True)
    def __str__(self):    
        return self.nomeLoja

class tab_fornecedor(models.Model):
    nomeFornecedor = models.CharField(max_length=60, blank=False, unique=True)
    endereco = models.CharField(max_length=60, blank=False)
    def __str__(self):
        return self.nomeFornecedor

class tab_produto (models.Model):
    nomeProduto = models.CharField(max_length=60, blank=False)
    descricao = models.CharField(max_length=60, blank=False)
    tamanho = models.CharField(max_length=60, blank=False)
    mEmpacotamento = models.CharField(max_length=60, blank=True)
    codBarras = models.IntegerField(blank=False, null=False, unique=True)
    marca = models.CharField(max_length=60, blank=False)
    # ManytoMany Below
    fornecedores = models.ManyToManyField(tab_fornecedor, related_name= "fornece")
    def __str__(self):    
        return self.nomeProduto

class tab_inventario(models.Model):
    qtdEstoque = models.IntegerField(default=0, blank=False, null=False)
    estoquePadrao = models.IntegerField(default=0, blank=False, null=False)
    preco = models.FloatField(default=0, blank=False, null=False)
    # ForeingKey Below    
    produto = models.ForeignKey(tab_produto, on_delete=models.CASCADE)
    loja = models.ForeignKey(tab_loja, on_delete=models.CASCADE)
    
class tab_pedido(models.Model):
    choice_tipo_venda=(
        ('V','Virtual'),
        ('F','Fisico')
    )
    data = models.DateField(blank=False, null= False)
    tipoVenda = models.CharField(max_length=1, choices = choice_tipo_venda, blank=False, null=True)
    totalPedido = models.FloatField(default=0.0, blank=False, null=False)
    # ForeingKey Below
    cliente = models.ForeignKey(tab_cliente,blank=True, null=True, on_delete=models.CASCADE)
    dependente = models.ForeignKey(tab_dependente, default= 0 ,blank=True, null=True ,on_delete=models.CASCADE)
    
class tab_item(models.Model):
    quantidade = models.IntegerField(blank=False, null=False)
    subTotal = models.FloatField(default=0.0, blank=False, null=False)
    # ForeingKey Below
    inventario= models.ForeignKey(tab_inventario, on_delete=models.CASCADE)
    pedido = models.ForeignKey(tab_pedido, on_delete=models.CASCADE)

lojasvarejistasapp/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import tab_cliente, tab_dependente, tab_fornecedor, tab_inventario, tab_item, tab_loja, tab_pedido, tab_produto
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.db import IntegrityError
# Create your views here.

##############################################
#                  HOME
##############################################
def home(request):
    return render(request, 'home.html')


##############################################
#                  CLIENTES
##############################################
def cliente(request):
    clientes = tab_cliente.objects.all()
    context = {'clientes':clientes}
    return render(request, 'cad_cliente.html', context)

def cadastrar_cliente(request):

    if request.method == 'POST':
        nome = request.POST.get('nome')
        cpf = request.POST.get('cpf') 
        telefone = request.POST.get('telefone')
        endereco = request.POST.get('endereco') 
        # Criando uma instância do modelo tab_cliente com os dados recebidos
        novo_cliente = tab_cliente(
            nomeCliente=nome,
            cpf=cpf,
            telefone=telefone,
            endereco=endereco,
            programaPTS=0, #valor padrão para o programaPTS
            totalPontos=0  #valor padrão para totalPontos
        )
        try:
            novo_cliente.save()
            messages.success(request, 'Cliente cadastrado com sucesso!')
        except Exception as e:
            messages.error(request, f'{e}')

    clientes = tab_cliente.objects.all()
    context = {'clientes':clientes}

    return render(request, 'cad_cliente.html', context)

def excluir_cliente(request, cliente_id):
    cliente = tab_cliente.objects.get(id=cliente_id)

    try:
        cliente.delete()
        messages.success(request, 'Cliente excluido com sucesso!')
    except Exception as e:
        messages.error(request, f'{e}')        

    #Busca todos os clientes do banco de dados já cadastrados.
    clientes = tab_cliente.objects.all()
    context = {'clientes':clientes}

    return render(request, 'cad_cliente.html', context)

def editar_cliente(request, cliente_id):

    cliente = get_object_or_404(tab_cliente, id=cliente_id)
    clientes = tab_cliente.objects.all()

    if request.method == 'POST':
        cliente.nomeCliente = request.POST.get('nome')
        cliente.cpf = request.POST.get('cpf')
        cliente.telefone = request.POST.get('telefone')
        cliente.endereco = request.POST.get('endereco')
        # Atualize os outros campos conforme necessário

        cliente.save()  # Salva as alterações no banco de dados

        context = {'clientes': clientes, 'cliente': cliente}
        return render(request, 'cad_cliente.html', context)

    context = {'clientes': clientes, 'cliente': cliente}
    return render(request, 'cad_cliente.html', context)


##############################################
#                 DEPENDENTES
##############################################
def dependente(request):
    dependentes = tab_dependente.objects.all()
    clientes = tab_cliente.objects.all()
    context = {'dependentes':dependentes, 'clientes':clientes}
    return render(request, 'cad_dependente.html', context)

def cadastrar_dependente(request):
    if request.method == 'POST':
        nome = request.POST.get('nome')
        parentesco = request.POST.get('parentesco') 
        cliente_id = request.POST.get('cliente')

        cliente = get_object_or_404(tab_cliente, pk=cliente_id)

        novo_dependente = tab_dependente(
            nomeDependente=nome,
            parentesco=parentesco,
            Cliente=cliente
        )
        try:
            novo_dependente.save()
            messages.success(request, 'Dependente cadastrado com sucesso!')
        except Exception as e:
            messages.error(request, f'{e}')

    dependentes = tab_dependente.objects.all()
    clientes = tab_cliente.objects.all()
    context = {'dependentes':dependentes, 'clientes':clientes}
    return render(request, 'cad_dependente.html', context=context)

def excluir_dependente(request, dependente_id):
    dependente = tab_dependente.objects.get(id=dependente_id)
    try:
        dependente.delete()
        messages.success(request, 'Excluido com sucesso!')
    except Exception as e:
        messages.error(request, f'{e}')  

    dependentes = tab_dependente.objects.all()
    clientes = tab_cliente.objects.all()
    context = {'dependentes':dependentes, 'clientes':clientes}
    return render(request, 'cad_dependente.html', context=context)

def editar_dependente(request, dependente_id):
    dependente = get_object_or_404(tab_dependente, id=dependente_id)
    clientes = tab_cliente.objects.all()

    if request.method == 'POST':
        try:
                nome = request.POST.get('nome')
                parentesco = request.POST.get('parentesco')
                cliente_id = request.POST.get('cliente')

                cliente = get_object_or_404(tab_cliente, pk=cliente_id)

                dependente.nomeDependente = nome
                dependente.parentesco = parentesco
                dependente.Cliente = cliente

                dependente.save()
                messages.success(request, 'Dependente editado com sucesso!')
                # Recarregando dependente após salvar as mudanças
                dependente = get_object_or_404(tab_dependente, id=dependente_id)
                return redirect('dependente')  # Redirecionar para a página correta após a edição
        except Exception as e:
            messages.error(request, f'{e}')  
    
    dependentes =  tab_dependente.objects.all()   
    context = {'dependente': dependente, 'clientes': clientes, 'dependentes':dependentes}
    return render(request, 'cad_dependente.html', context=context)


##############################################
#                 PRODUTOS
##############################################
def produto(request):
    produtos = tab_produto.objects.all()
    lojas = tab_loja.objects.all()
    fornecedores = tab_fornecedor.objects.all()
    context = {'produtos':produtos, 'lojas':lojas, 'fornecedores':fornecedores}
    return render(request, 'cad_produto.html', context)


def cadastrar_produto(request):

    if request.method == 'POST':
        nome = request.POST.get('nome')
        descricao = request.POST.get('descricao')
        tamanho = request.POST.get('tamanho')
        mEmpacotamento = request.POST.get('mEmpacotamento')
        codBarras = request.POST.get('codBarras')
        marca = request.POST.get('marca')
        fornecedores = request.POST.getlist('fornecedor')
        qtdProduto = request.POST.get('qtdProduto')
        estoquePdr = request.POST.get('estoquepdr')
        preco = request.POST.get('preco')
        loja = request.POST.get('loja')

        novo_produto = tab_produto(
            nomeProduto=nome,
            descricao=descricao,
            tamanho=tamanho,
            mEmpacotamento=mEmpacotamento,
            codBarras=codBarras,
            marca=marca,
        )

        try:
            novo_produto.save()

            for fornecedor_id in fornecedores:
                fornecedor = get_object_or_404(tab_fornecedor, pk=fornecedor_id)
                novo_produto.fornecedores.add(fornecedor)

            loja_obj = get_object_or_404(tab_loja, pk=loja)

            produto_inventario = tab_inventario(
                qtdEstoque=qtdProduto,
                estoquePadrao=estoquePdr,
                preco=preco,
                produto=novo_produto,
                loja=loja_obj,
            )
            produto_inventario.save()

            messages.success(request, 'Produto cadastrado com sucesso!')
        except Exception as e:
            messages.error(request, f'Erro ao cadastrar produto: {e}')

    produtos = tab_produto.objects.all()
    lojas = tab_loja.objects.all()
    fornecedores = tab_fornecedor.objects.all()
    context = {'produtos': produtos, 'lojas': lojas, 'fornecedores': fornecedores}
    return render(request, 'cad_produto.html', context)


def editar_produto(request, produto_id):

    produto = tab_produto.objects.all()
    lojas = tab_loja.objects.all()
    fornecedores = tab_fornecedor.objects.all()

    if produto_id:
        produto = get_object_or_404(tab_produto, id=produto_id)
        inventario = get_object_or_404(tab_inventario, produto=produto)

    if request.method == 'POST':
        try:
                nome = request.POST.get('nome')
                descricao = request.POST.get('descricao')
                tamanho = request.POST.get('tamanho')
                mEmpacotamento = request.POST.get('mEmpacotamento')
                codBarras = request.POST.get('codBarras')
                marca = request.POST.get('marca')
                fornecedores_novos = request.POST.getlist('fornecedor')
                qtdProduto = request.POST.get('qtdProduto')
                estoquePdr = request.POST.get('estoquepdr')
                preco_str = request.POST.get('preco')
                # Substituir vírgula por ponto para garantir que seja um número float válido
                preco = float(preco_str.replace(',', '.'))
                loja_id = request.POST.get('loja')

                # Atualiza os campos do produto existente
                produto.nomeProduto = nome
                produto.descricao = descricao
                produto.tamanho = tamanho
                produto.mEmpacotamento = mEmpacotamento
                produto.codBarras = codBarras
                produto.marca = marca

                produto.fornecedores.clear()  # Limpa os fornecedores existentes
                for fornecedor_id in fornecedores_novos:
                    fornecedor = get_object_or_404(tab_fornecedor, pk=fornecedor_id)
                    produto.fornecedores.add(fornecedor)

                # Atualiza o inventário do produto existente

lojasvarejistasapp/templates/cad_cliente.html
{% extends 'bases/base.html' %}
{% load static %}

{%block 'head'%}
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{%url 'home'%}"><i class="bi bi-house-door-fill text-secondary"></i></a></li>
    <li class="breadcrumb-item active" aria-current="page">Clientes</li>
  </ol>
</nav>
{%endblock 'head'%}

{%block 'main'%}
          <div class="main">
            <h5 class="mb-4 mt-4 text-secondary">Cadastro de Cliente</h5>
            
            {% if messages %}
                {% for message in messages %}
                <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

            <form method="POST" action="{% if cliente.id %}{% url 'editar_cliente' cliente.id %}{% else %}{% url 'cadastrar_cliente' %}{% endif %}" class="row g-3">
              {% csrf_token %}
                <div class="col-md-4">
                  <label for="inputnome" class="form-label"><small>Nome</small></label>
                  <input type="text" name= "nome" class="form-control"  value="{{cliente.nomeCliente}}" placeholder="Nome Completo">
                </div>

                <div class="col-md-4">
                  <label for="inputemail" class="form-label"><small>CPF</small></label>
                  <input type="text" name= "cpf" class="form-control" value="{{cliente.cpf}}"  placeholder="Somente números">
                </div>

                <div class="col-md-4">
                  <label for="inputtelefone" class="form-label"><small>Telefone</small></label>
                  <input type="text" name= "telefone" class="form-control" value="{{cliente.telefone}}"  placeholder="Somente números">
                </div>

                <div class="col-md-6">
                  <label for="inputtipopessoa" class="form-label"><small>Endereço</small></label>
                  <input type="text" name= "endereco" class="form-control" value="{{cliente.endereco}}"  placeholder="Endereço completo">
              </div>
            
                <div class="col-md-6 align-items d-flex justify-content-end align-items-end">
                  <a href="{% url 'home' %}" class="btn btn-outline-danger">Sair</a>
                {% if cliente.id %}
                  <button type="submit" class="btn btn-success ms-2">Alterar</button>
                {% else %}
                  <button type="submit" class="btn btn-success ms-3">Salvar</button>
                {% endif %}
                </div>

            </form><!-- End No Labels Form -->
              <hr class="border-secondary">
              <h5 class="mb-4 mt-4 text-secondary">Clientes cadastrados</h5>
              <div class="shadow" style="max-height: 280px; overflow-y: auto;">
              <table class="table table-hover" >
                <thead style="position: sticky; top: 0; background-color: white;">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Cliente</th>
                    <th scope="col">CPF</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">Endereço</th>
                    <th scope="col">Programa Pts</th>
                    <th scope="col">Total Pts</th>
                    <th scope="col">Editar</th>
                    <th scope="col">Excluir</th>
                  </tr>
                  
                  <tbody>
                    {% for cliente in clientes %}
                    <tr> <!-- Inserir variáveis do Django Aqui -->
                      <td> {{cliente.id}} </td>
                      <td> {{cliente.nomeCliente}} </td>
                      <td> {{cliente.cpf}} </td>
                      <td> {{cliente.telefone}}</td>
                      <td> {{cliente.endereco}}</td>
                      <td> {% if cliente.programaPTS %}Sim {%else%} Não {%endif%}</td>
                      <td> {{cliente.totalPontos}} </td>
                      <td> <a href="{% url 'editar_cliente' cliente.id %}">  <i class="bi bi-pencil text-dark"></i></a> </td>
                      <td> <a href="{% url 'excluir_cliente' cliente.id %}"> <i class="bi bi-trash text-danger"></i></a> </td>
                    </tr>
                    {% endfor %}
                  </tbody>

                </thead>
                <tr>

                </tr>

              </table>
            </div>
          </div>
{%endblock 'main'%}

lojasvarejistasapp/templates/cad_produto.html
{% extends 'bases/base.html' %}
{% load static %}


{%block 'head'%}
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{%url 'home'%}"><i class="bi bi-house-door-fill text-secondary"></i></a></li>
    <li class="breadcrumb-item active" aria-current="page">Produto</li>
  </ol>
</nav>
{%endblock 'head'%}

{%block 'main'%}
          <div class="main">
            <h5 class="mb-4 mt-4 text-secondary">Cadastro de Produto</h5>
              {% if messages %}
                  {% for message in messages %}
                  <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% endif %}">
                          {{ message }}
                      </div>
                  {% endfor %}
              {% endif %}
              <form method="POST" action="{% if produto.id %}{% url 'editar_produto' produto.id %}{% else %}{% url 'cadastrar_produto' %}{% endif %}" class="row g-3">
                {% csrf_token %}
                <div class="col-md-3">
                  <label for="inputnome" class="form-label"><small>Nome Produto</small></label>
                  <input name="nome" class="form-control" placeholder="" value="{{ produto.nomeProduto }}">
                </div>
                
                <div class="col-md-2">
                  <label for="inputemail" class="form-label"><small>Descrição</small></label>
                  <input name="descricao" class="form-control" placeholder="" value="{{ produto.descricao }}">
                </div>
                
                <div class="col-md-2">
                  <label for="inputtelefone" class="form-label"><small>Marca</small></label>
                  <input name="marca" class="form-control" placeholder="" value="{{ produto.marca }}">
                </div>
                
                <div class="col-md-2">
                  <label for="inputtipopessoa" class="form-label"><small>Código Barras</small></label>
                  <input name="codBarras" class="form-control" placeholder="Somente números" value="{{ produto.codBarras }}">
                </div>
                
                <div class="col-md-3">
                  <label for="inputtipopessoa" class="form-label"><small>Quantidade Produto</small></label>
                  <input type="number" name="qtdProduto" class="form-control" placeholder="" value="{{ inventario_produto.qtdEstoque }}">
                </div>
                
                <div class="col-md-2">
                  <label for="inputtipopessoa" class="form-label"><small>Tamanho</small></label>
                  <input name="tamanho" class="form-control" placeholder="" value="{{ produto.tamanho }}">
                </div>
                
                <div class="col-md-2">
                  <label for="inputtipopessoa" class="form-label"><small>Empacotamento</small></label>
                  <input name="mEmpacotamento" class="form-control" placeholder="" value="{{ produto.mEmpacotamento }}">
                </div>
                
                <div class="col-md-2">
                  <label for="inputtipopessoa" class="form-label"><small>Estoque Padrão</small></label>
                  <input name="estoquepdr" class="form-control" placeholder="" value="{{ inventario_produto.estoquePadrao}}">
                </div>
                
                <div class="col-md-2">
                  <label for="inputtipopessoa" class="form-label"><small>Preço</small></label>
                  <input name="preco" class="form-control" placeholder="" value="{{ inventario_produto.preco }}">
                </div>
                
                <div class="col-md-2">
                  <label for="loja" class="form-label"><small>Loja</small></label>
                  <select name="loja" id="loja" class="form-select">
                    <option value="">Selecione o loja</option>
                    {% for loja in lojas %}
                      <option value="{{ loja.id }}" {% if inventario_produto and loja.id == inventario_produto.loja.id %} selected {% endif %}>{{ loja.nomeLoja }}</option>
                    {% endfor %}
                  </select>
                </div>
                
                <div class="col-md-2">
                  <label for="fornecedor" class="form-label"><small>Fornecedor</small></label>
                  <select name="fornecedor" id="fornecedor" class="form-select">
                    <option value="">Selecione o fornecedor</option>
                    {% for fornecedor in fornecedores %}
                      <option value="{{ fornecedor.id }}" {% for fornecedor_produto in produto.fornecedores.all %} {% if fornecedor_produto.id == fornecedor.id %} selected {% endif %} {% endfor %}>{{ fornecedor.nomeFornecedor }}</option>
                    {% endfor %}
                  </select>
                </div>
                

                <div class="col-md-12 align-items d-flex justify-content-end align-items-end">
                  <a href="{% url 'home' %}" class="btn btn-outline-danger">Sair</a>
                      {% if produto.id %}
                        <button type="submit" class="btn btn-success ms-2">Alterar</button>
                      {% else %}
                        <button type="submit" class="btn btn-success ms-3">Salvar</button>
                      {% endif %}
                </div>

              </form><!-- End No Labels Form -->
              <hr class="border-secondary">
              <h5 class="mb-4 mt-4 text-secondary">Produtos cadastrados</h5>
              <table class="table table-hover shadow">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Produto</th>
                    <th scope="col">Descrição</th>
                    <th scope="col">Marca</th>
                    <th scope="col">Cod. Barras</th>
                    <th scope="col">Tamanho</th>
                    <th scope="col">Empaco.</th>
                    <th scope="col">Fornecedor</th>
                    <th scope="col">Loja</th>
                    <th scope="col">Estq. Padrão</th>
                    <th scope="col">Saldo Estq.</th>
                    <th scope="col">Preço</th>
                    <th scope="col">Editar</th>
                    <th scope="col">Excluir</th>
                  </tr>
                </thead>
                <tbody>
                  <!-- Inserir variáveis do Django Aqui -->
                  {% for produto in produtos %}
                    <tr>
                      <td>{{ produto.id }}</td>
                      <td>{{ produto.nomeProduto }}</td>
                      <td>{{ produto.descricao }}</td>
                      <td>{{ produto.marca }}</td>
                      <td>{{ produto.codBarras }}</td>
                      <td>{{ produto.tamanho }}</td>
                      <td>{{ produto.mEmpacotamento }}</td>
                      <td>
                        {% for fornecedor in produto.fornecedores.all %}
                          {{ fornecedor.nomeFornecedor }}
                          {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                      </td>
                      <td>{{ produto.tab_inventario_set.all.0.loja.nomeLoja }}</td>
                      <td>{{ produto.tab_inventario_set.all.0.estoquePadrao }}</td>
                      <td>{{ produto.tab_inventario_set.all.0.qtdEstoque }}</td>
                      <td>{{ produto.tab_inventario_set.all.0.preco }}</td>
                      <td><a href="{% url 'editar_produto' produto.id %}"><i class="bi bi-pencil text-dark"></i></a></td>
                      <td><a href="{% url 'excluir_produto' produto.id %}"><i class="bi bi-trash text-danger"></i></a></td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
              
          </div>
{%endblock 'main'%}